title: Ravisher Dhillon # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h6>Machine Learning | MLOPS</h6>
  <h6>Software Engineer | Architect Enterprise Application</h6>
  <br><br>
  <img src='/images/aws-badge.png' />
  <br><br>
  <a href="https://www.linkedin.com/in/ravishersinghdhillon/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
