title: Ravisher Dhillon # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer | Machine Learning | Big Data
  <br><br>
  Seasoned Software Engineer with interest in scaling machine learning workflows
  <br><br>
  <a href="https://www.linkedin.com/in/ravishersinghdhillon/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
